name: 'ESLint PR review'
description: 'It lints with ESLint'
branding:
  icon: aperture
  color: blue
author: 'rpkak'
inputs:
  project-root:
    required: false
    description: 'The path of the npm project root'
    default: '.'
  src:
    required: false
    description: 'The path of the source. Relative to project-root'
    default: '.'
  github-token:
    required: true
    description: The GitHub token, to access to this repo
  eslint-format:
    required: false
    description: 'The ESLint format for displaying in log. View https://eslint.org/docs/user-guide/formatters/'
    default: stylish
  approve-mode:
    required: false
    description: 'Use "approve-always" if the PR should approved even if it is approved already. Use "after-change-request" otherwise.'
    default: approve-always
  extensions:
    required: false
    description: 'Comma separated list of file the fileendings, ESLint should lint.'
    default: js,jsx,ts,tsx
runs:
  using: 'docker'
  image: 'docker.pkg.github.com/rpkak/eslint-pr-review/eslint-pr-review:1.2.0.test'
  args:
    - ${{ inputs.project-root }}
    - ${{ inputs.src }}
    - ${{ inputs.github-token }}
    - ${{ inputs.eslint-format }}
    - ${{ inputs.approve-mode }}
    - ${{ inputs.extensions }}
